### ISSUE TITLE
Clearcasting from Arcane concentration not working as in retail

### ISSUE THREAD

**Issue by Scrybatog** [elysium-project/bug-tracker#157]
In retail in 1.12 if you cast blizzard on 20 mobs there was a near 100% chance of clearcasting as it checked per monster hit.

On Nighthaven it seems to be a flat 10% no matter how many targets you hit, which heavily devalues the talent in aoe grinding, separating this server from retail quit a bit for mages.

**Comment by Terranzin** [comment]
You´ll need more solid proof then speculation. We have been testing this earlier and showned it´s correct. I´ll deny this one for now, since it´s still 10% on each single mob (1/10th chance) it´s still not alot, and back in vanilla it wasnt even close to 100% of the times, I know this by experience since I didnt quest from 55 - 60 instead farmed in EPL and WPL.
