### ISSUE TITLE
ELemental Spell power not working

### ISSUE THREAD

**Issue by Scrybatog** [elysium-project/bug-tracker#158]
I have 51 frost spell power and it does not effect Blizzard's damage at all.

([Cast Time] / 3.5) / 2 = [Coefficient]) is the formula that should be used to determine value of spell power on aoe spells, but appears to not be working.

**Comment by YaboyJimmyrustle** [comment]
The difference between Blizzard damage with no gear, +51 spell damage and healing gear, and +51 frost damage gear is marginal. I will look into whether the coefficient for blizzard damage needs to include more damage based on spell damage and the nature of AOE spells.

**Conditions:**
Level 55 Mage
Blizzard (Rank 6) spellid 10187
Targets: Skeletal Flayer and Slavering Ghouls, Western Plaguelands


No armor, no spell damage bonus
![no spell damage](https://user-images.githubusercontent.com/36592168/36519063-232ec680-173e-11e8-8208-30e03d768f5a.png)

+51 Frost damage (Several minor stats from gear: +10 int, +3 spirit)
![51 frost spell damage](https://user-images.githubusercontent.com/36592168/36519078-33fac6b2-173e-11e8-8283-97e62ee9263e.png)


+51 Damage and Healing (Several minor stats from gear: +16 int, +16 spirit, +6 stam)
![51 damage and healing](https://user-images.githubusercontent.com/36592168/36519083-3a8a2874-173e-11e8-8b39-174e83e798cb.png)

**Comment by YaboyJimmyrustle** [comment]
After further research, I have found the formula for bonus Blizzard spell damage is functioning as intended.

**The formula to determine bonus spell damage for Blizzard (Rank 6) is based on 4 categories:**
Cast time - Since Blizzard is a channeled spell it falls within the 3.5 qualifier. (3.5/3.5) = [1]
AOE - Blizzard is an aoe spell and as such has a modifier of 0.333 [.333]
Effect - Blizzard has no build in snare effect and is given full spell power bonus in this category. [1]
Level - Blizzard (Rank 6) is learned at level 60 and receives full spell power bonus. [1]

The final formula to determine the spell power bonus of Blizzard (Rank 6) based on +51 Frost Damage gear is: 
**(3.5/3.5) * .333 * 1 * 1 = .333**

Blizzard ticks 8 times throughout the channeling, 1 tick per second. Based on +51 frost spell damage gear the formula would look like this:

**51 * .333 = 16.983 bonus damage overall
16.983/8 = ~2.123 bonus damage per Blizzard (Rank 6) tick**

This is backed up by the pictures I provided before as the difference between both +51 frost/damage and healing gear is doing slightly more minimum and maximum damage than with no gear or +0 spell damage (164 vs 162 respectively). Although a marginal difference, it is functioning and contributing to your Blizzard damage. Depending on what rank Blizzard you are using, it may also have a modifier impacting the frost damage bonus even further.

I hope this helped! Please let me know if you have anymore questions regarding this issue.
