### ISSUE TITLE
Quest: Galak Messenger appears to be missing

### ISSUE THREAD

**Issue by Navashed** [elysium-project/bug-tracker#182]
NPC 10617 - Galak Messenger does not spawn.

He drops an item which begins a quest chain.

**Comment by Firestoat** [comment]
This must be a recent development, because I obtained the quest starter item 2 days ago with 2 different characters. The issue is that the level 25-27 centaur area with the cave with the Sacred Flame item is constantly camped with Horde questing there, and the Galak Messenger is nearly always killed before he gets a chance to do the longer part of his patrol route.

I picked him off early by killing Centaur in Camp E'thok and constantly checking the East side entrance to the camp for his approach. When he spawns he roams into that camp first, then doubles back to start his patrol route that takes him to his death by other players at the site I described above.
