### ISSUE TITLE
NIGHTHEAVEN PVP DRUID RAKE SKILL DONT SCALING WITH ATTACK POWER

### ISSUE THREAD

**Issue by morbidsatyr** [elysium-project/bug-tracker#187]
NIGHTHEAVEN PVP DRUID RAKE SKILL DONT SCALING WITH ATTACK POWER

**Comment by morbidsatyr** [comment]
https://forum.nostalrius.org/viewtopic.php?f=6&t=10688&sid=0690a52ba5cc6d92a3e2af8f05152ce4&start=10 here list AP scaling coef.

**Comment by Navashed** [comment]
Confirmed.

Rake is currently not scaling with AP (both the direct damage portion and the DoT portion).

Since this server uses 1.12 mechanics, the patch 1.12 changes to AP scaling should be in the game. In the patch 1.12 notes, Eviscerate, Rupture, Garrote, and Ferocious Bite are said to now scale with AP:
http://wowwiki.wikia.com/wiki/Patch_1.12.0

However, Rip and Rake are not mentioned. Most likely, their AP scaling was added in the same patch and Blizzard forgot to mention them.
This theory is corroborated by an upvoted comment on old thottbot:
https://web.archive.org/web/20070503171915/http://www.thottbot.com:80/s9896

The comment states Rip scales with AP in 1.12 just like the analogous Rogue ability, Rupture.

We can safely assume that, since Rip's scaling was left off the patch notes, Rake's was also.

The 6% scaling on the DoT portion in the thread you linked is corroborated by old data from TBC:
https://web.archive.org/web/20070503161040/http://www.thottbot.com:80/s9904
http://web.archive.org/web/20071104130030/http://wow.allakhazam.com:80/db/spell.html?wspell=9904

No data exists about Rake from between patch 1.12 and patch 2.0. Therefore the scaling behavior, if any of the direct damage portion of Rake between patch 1.12 and 2.0 is unknown.

It is my opinion that the TBC functionality of Rake as seen on those old databases is likely the correct functionality from patch 1.12 onward, meaning the direct damage portion of Rake should also scale with AP according to the formula seen in those links.

**Comment by Pmt112** [comment]
well look i dont think this is right because
now when i fight high armor or low armor mob or what
when i want to build combo points
normally i have choice but now rake is always better
as long as its not already active
on top of that it just gives rake too much damage
i dont think this is supposed to scale with AP at all
this means more mindless rotation and a little overpower
instead of more interesting play^^

**Comment by Pmt112** [comment]
i dont think thats blizzlike and i think bad change
