### ISSUE TITLE
A Plague Upon Thee (part 3) bug/script issue

### ISSUE THREAD

**Issue by Rewston** [elysium-project/bug-tracker#234]
So I/we are not able to accept the quest A Plague Upon Thee (part 3) due to not being able to interact with the "Barrel of Plagueland Termites" on the crate at the sawmill.
Been trying the usual, abandon and take the quest again, relog but they don't work.
It just stands there gushing  smoke.
![karonu - a plague upon thee](https://user-images.githubusercontent.com/34864209/34360035-5cd8a616-ea5d-11e7-90ba-cf0b85f151ee.png)

**Comment by Egregious** [comment]
So, there seems to be a bit wrong here. 

I was able to complete A Plague Upon Thee (part 2) quest#5902 by clicking on the Termite Barrel. It provides you with a (Completed) quest A Plague Upon Thee (part 3) quest#6390 which you then can go hand into Mickey Levine (for Horde). No further action is required, you are given stage 3 of the quest in its Completed form.

However, I do not believe the quest is supposed to function in this fashion. During A Plague Upon Thee (part 2) quest#5902 the Termite Barrel above the Northridge Lumber Mill Crate should not be visible. Instead there should be a prompt within the Northridge Lumber Mill Crate to place the Termite Barrel upon said crate. After that, the Termite Barrel should become visible and being to smoke. You should then interact with the smoking Termite Barrel to receive the followup A Plague Upon Thee (part 3) quest#6390. The quest should already be completed and is ready to be handed into the appropriate NPC at The Bullwark (for Horde) or Chillwind Camp (for Alliance).

**Comment by twink** [comment]
I have tried both (alliance and horde) quests, for me everything fine.
I need better description from QA or someone other what exactly is a problem.

**Comment by tubiakou** [comment]
Egregious is correct.

### Expected Behaviour
The smoking barrel should not be visible on top of the crate until the following conditions are met:
1. You are on **_A Plague Upon Thee (part 2)_** (_quest ID 5902_).
2. You have a **_Barrel of Plagueland Termites_** (_item ID 15044_) in your inventory.
3. You click on the crate (at this point item 15044 should disappear from inventory, and appear on top of the crate).

### Actual Behaviour
Simply travel to the crate, without having any of the **_A Plague Upon Thee_** quests, and/or without having item 15044 in your inventory.  You will immediately see a smoking barrel on top of the crate.

Hopefully this provides enough information to move this issue forward.  Replacing the "invalid" label with "Confirmed".

**Comment by Giperionn** [comment]
Hello @Rewston . Thanks for reporting.
Part two can be completed by "Northridge Lumber Mill Crate". Right after that, you will be able to see a barrel on top of crate, that give part three of quest chain.
Fix will be available at next server update.
