### ISSUE TITLE
In dreams quest id= 5944

### ISSUE THREAD

**Issue by jontehack** [elysium-project/bug-tracker#244]
The quest in Dreams quest id 5944 is bugged beyond belief, even with gm supervision of it and they agreed it to be bugged,

Npc stops moving and is like the most confusing part of their life deciding left or right, the last part is bugged beyond comparison sometimes the npc go up into the air fighting leaving them unable to continue. 

Several tries on quest it all starts bugging at the gate down the hill.

**Comment by Terranzin** [comment]
1: First hallway, at times he gets stuck here because he levitates above the ground
![image](https://user-images.githubusercontent.com/25831382/34456390-1528293c-ed95-11e7-9cac-87b1aae9403e.png)

2: When this mob aggros the NPC runs to the location of Fordring but Fording is stuck in place and does not attack.
![image](https://user-images.githubusercontent.com/25831382/34456398-534c2c9a-ed95-11e7-9f2b-a2364c08ad0a.png)

3: When one of these mobs aggros Fordring, they do NOT even run to his location, Fording gets stuck in spot and also the mobs.
![image](https://user-images.githubusercontent.com/25831382/34456413-c03ca2d0-ed95-11e7-8558-dd08c450607a.png)

![image](https://user-images.githubusercontent.com/25831382/34456404-71868dfe-ed95-11e7-95b3-255c15abfc93.png)

4: When they finally meet at the tower to fight, the RP event is correct, the guards spawns and everything, and they start attacking fordring + players, but Fordring does nothing. Killing the mobs doesnt complete anything. Fordring stays in spot until he despawns.
![image](https://user-images.githubusercontent.com/25831382/34456409-a7da5e76-ed95-11e7-8990-32a2d44b73dc.png)
![image](https://user-images.githubusercontent.com/25831382/34456412-b30d54ec-ed95-11e7-845a-3752355e8d12.png)

**Comment by jbshifter** [comment]
Tried to do it about 20min ago Taelan is still having issues with certain guards, would be awesome if GM's would just complete the quest for those who are on it while the devs get the bugs/issues sorted out.  This quest is easily solo'able if the scrip it working properly...
