### ISSUE TITLE
Pattern: Azure Silk Gloves not spawning at vendor

### ISSUE THREAD

**Issue by SmokealotapotimuS** [elysium-project/bug-tracker#267]
Wenna Silkbeard hasn't had a recipe to purchase in stock. Based on what it says here:
http://db.vanillagaming.org/?item=7114 
Wenna Silkbeard should have an infinite stock. The site could easily be wrong but, I've been checking frequently for the pattern the last couple days and haven't seen it.
I should also say I've scanned the auction house and haven't even seen the pattern, nor the gloves posted.

**Comment by SmokealotapotimuS** [comment]
I should also say I've scanned the auction house and haven't even seen the pattern, nor the gloves posted.

**Comment by Terranzin** [comment]
Hello,

I´ve reviewed your issue and Wenna Silkbeard does in matter of fact have the item in stock at times, but it isn´t there 100%. Sometimes she sells some of them at some resets she sells just one of them and this is how she´s working/intended. 

You´re probably unlucky since there´s loads of players roaming this place and eventually when the reset is, someone might have already grabbed it.

![image](https://user-images.githubusercontent.com/25831382/34579613-f86fc932-f189-11e7-9b47-5cad70cdbcd4.png)
