### ISSUE TITLE
Free at Last! Escort NPC

### ISSUE THREAD

**Issue by Asipdk** [elysium-project/bug-tracker#269]
While performing the quest, the NPC doesn't care AT ALL about any mobs attacking her or anything at all. She just walks through them. I don't know if thats how the NPC is supposed to be, but based on experience and other quests, she should be attacking them at the very least instead of forcing the player to continuously kite enemies while staying with her.
  Quest takes place in Thousand Needles

**Comment by Terranzin** [comment]
I´ve reviewed your issue and Can´t reproduce the error. I would think the issue was because when server havent restarted in awhile, quests starts doing fishy buisness.

Anyway I started the quest and mobs started instantly attacking her
![image](https://user-images.githubusercontent.com/25831382/34579964-6169b24e-f18b-11e7-8bd0-ee795e0506a2.png)
