### ISSUE TITLE
Isha Awak

### ISSUE THREAD

**Issue by Asipdk** [elysium-project/bug-tracker#270]
Isha Awak is located in the Merchant Coast of the barrens south of Mahren's hut when attempting to aggro the mob it took several attempts for it to actually aggro on and one of the times it decided it would just then disengage and swim back on its patrol.

**Comment by Terranzin** [comment]
I´ve reviewed your issue. So I aggro the mob I was swimming around the whole area with him as aggro (not to long since they do disengage at long range).

I couldnt reproduce the error you´re speaking of, he evades once you go up on land which is working as intended and like mentioned above, I took him to different places around his patrolling area and he didn´t disengage. You´ll need to provide more proof as video or something and exactly how to reproduce it.

![image](https://user-images.githubusercontent.com/25831382/34580194-639ad2ae-f18c-11e7-96f9-9ba43af21858.png)
