### ISSUE TITLE
Samophlange

### ISSUE THREAD

**Issue by glorfarion** [elysium-project/bug-tracker#286]
My 12 priest did samophlange quest in a group. Opened console, turned the three knobs, opened console, got next quest ok. Then we killed the boss and got the key. My two party members completed the quest just fine, but I opened the console with the key and it said I "didn't qualify" for the next quest in the chain. I tried the console again, but it was not clickable. No more key in my inventory. No samophlange item in my inventory (yes, I had bag space). Tried the quest giver, but he no longer offered the quest. I lost the reward and the chance at completing the chain.

**Comment by Navashed** [comment]
Confirmed.

This is because the final quest in the chain (Quest 902) currently requires level 13.

Steps 2-4 in the quest chain should all require level 11:
Quest 900 - Samophlange (2)
Quest 901 - Samophlange (3)
Quest 902 - Samophlange (4)

https://web.archive.org/web/20070115075917/http://www.thottbot.com:80/?qu=902

**Comment by Colemata** [comment]
https://github.com/elysium-project/server/pull/3289
