### ISSUE TITLE
Stranglethorn Fever quest

### ISSUE THREAD

**Issue by Wowhun** [elysium-project/bug-tracker#378]
Retook Stranglethorn Fever quest from Bootybay many times and no matter what, **Witch Doctor Unbagwa never has the blue quest mark** which he takes Gorilla fangs to start the summoning of special gorillas till Mokk the savage comes, never been able to interact with him and many friends too.

**Comment by tubiakou** [comment]
I tested this on PTR, with the following steps:

1. Acquired the quest "Stranglethorn Fever" from Fin Fizracket.
2. Dropped the quest (since your description said you "retook" it.
3. Retook the quest successfully.
4. Travelled to Witch Doctor Unbagwa, and observed that he indeed did have the blue ? over his head.
5. Observed that the quest he had was "[45] Stranglethorn Fever" requiring 10 gorilla fangs, which is hte correct quest.
![image](https://user-images.githubusercontent.com/35384059/35604733-b3419a74-0611-11e8-9349-8bf6b1901658.png)
![image](https://user-images.githubusercontent.com/35384059/35604787-056c8d5e-0612-11e8-85f9-338829ead692.png)
