### ISSUE TITLE
buffs from elixirs dont work

### ISSUE THREAD

**Issue by trofan** [elysium-project/bug-tracker#394]
Elixir of Greater intellect (https://classicdb.ch/?item=9179) and Elixir of the Sages (https://classicdb.ch/?item=13447) dont give their +int and + spirit while I am already buffed by intellect buff (from mage) and spirit buff (from priest).
They gives only icon among other buffs on me, but dont counts.

**Comment by tubiakou** [comment]
I believe this is by design.  Potions, elixirs and oils will typically not stack with spells that have the same kind of effect.  They will stack with other potions/elixirs/oils, but again not with those having the same kind of effect.

## Example
Elixir of the Sages:  +18 to spirit.
Divine Spirit (Rank 3): +33 to spirit

1. If you cast Divine Spirit (rank 3) your spirit goes up by 33.  If you then drink Elixir of the Sages it will do nothing, because it's buff (+18) is smaller than the one you already have (+33 spirit).  Smaller buffs will have no effect on larger ones.

2. If instead you drink Elixir of the Sages (+18 spirit) and then cast Divine Spirit (+18 spirit), the buff on you changes from +18 to +33 spirit.  Larger buffs will replace smaller ones.
