### ISSUE TITLE
Tome of Valor

### ISSUE THREAD

**Issue by Nico133a** [elysium-project/bug-tracker#447]
I tried to do this quest but failed, then i abandoned it and tried to re accept it through the tome but i got the message "You are already on that quest" but no paladin quests in my log. Then i asked a mod who asked me to clear WDB folder which i did but it did not solve my problem. Then I deleted the tome of valor and went to stormwind to get a new one in hope of it resetting, now what happend is i got the quest from the pala-quest giver but this time no book(tome of valor) sadly the mission failed, but now im unable to either recieve "Tome of Valor" nor get the quest from the paladin-quest-giver.

**Comment by YaboyJimmyrustle** [comment]
Instead of going back to Stormwind to get another "Tome of Valor" from the Paladin quest-giver, you need to go back to Daphne Stilwell. She will give you the quest to protect her again, which once completed, will return you to the Stormwind Chapel for the reward of learning Sense Undead and item Bastion of Stormwind. Essentially, once you have accepted the quest from the Tome of Valor and accepted the quest to protect her from the Defias, you no longer need the Tome of Valor to complete this quest chain. Hope this helps!
