### ISSUE TITLE
clearcasting doesn't proc with aoe accordingly

### ISSUE THREAD

**Issue by xcuz** [elysium-project/bug-tracker#448]
clearcasting should proc accordingly to a more significantly number of mobs which it does not
i.e using arcane explosion should give a higher chance of having a proc with more tagged mobs not just _one_.

the same goes with flamestrike etc

**Comment by xcuz** [comment]
not fixed yet
19/2 - 2018

**Comment by Navashed** [comment]
Can you find proof that this behavior is Blizzlike for damage spells? This change would make AoE spam essentially free beyond a certain number of mobs.

I do know that it is true for buffs. AoE buffs had a separate chance to proc Clearcasting for each target buffed; in WotLK 25 mans, Gift of the Wild was a regular spell in the Moonkin rotation with 2pc T10 because it would proc Clearcasting every time (2pc T10 made Clearcasting into a damage buff).

**Comment by xcuz** [comment]
Every other private server I have been to were working like that if that should say something

Feenix
Nostalrius
Kronos
Scriptcraft
VanillaGaming
Rebirth
Valkyrie

The current clearcasting on this server has only like a 10% proc chance even if you even pull 10+ mobs

**Comment by Navashed** [comment]
Behavior of other private servers is not evidence of Blizzlike behavior. If you could find a video from vanilla (or even TBC) of a mage AoEing and seeing his clearcasting proc excessively, that would be proof.
