### ISSUE TITLE
Hezrul Bloodmark

### ISSUE THREAD

**Issue by SuperHeroesAlwaysdie** [elysium-project/bug-tracker#454]
Hi there !
How nice it is when you discover wow classic, isn it?
But then you arrive at this quest.
So here is my point, a quest, hard enough , and slow enough is on purpous to be made in group right?
this quest so could have this purpous when we see that most of the players succeed it in group.
But the reward, is only for 1 player.
It s like an escort, or a boss head that only 1 player can loot ^^ this could be removed and replaced to let
each player of the group get it.

Thanks for reading , this is just a proposition for a better world :)

**Comment by SuperHeroesAlwaysdie** [comment]
OUPS
the quest i m talking about is Counterattack!
http://classicdb.ch/?quest=4021

and i m talking about Piece of Krom'zar's Banner that only 1 player can have

**Comment by YaboyJimmyrustle** [comment]
As this is not a bug that can be reproduced, I am going to mark this issue as "Invalid." 

The way only one player can loot a piece of the banner after killing Krom'zar's is intentional. Killing the boss multiple times is not as tedious since the boss can be respawned by killing centaurs around his hut instead of waiting out a timer. Your suggestion for changing this will be taken into consideration, thank you!
