### ISSUE TITLE
Southsea mobs in lost rigger cove #3264

### ISSUE THREAD

**Issue by Terranzin** [elysium-project/bug-tracker#49]
From old bug-tracker:

> The bridge leading towards the two ships in tanaris lost rigger cove doesn't seem to be effected by my cone of cold damage. Rest of my spells like frost nova and blizzard are hitting them. I don't know if the bridge is bugged and if its a vanilla thing. Thanks

**Comment by Terranzin** [comment]
Hello,

Thanks for your report. I´ve now reviewed your issue and I cant reproduce the error you´re facing. I attempted using Cone of cold on all 4 bridges between the two ships.

![image](https://user-images.githubusercontent.com/25831382/32914073-9a5c3808-cb14-11e7-8c05-1960e91a35b5.png)

For now we´re closing the issue, if you manage to reproduce it, please provide a screenshot.

**Comment by Terranzin** [comment]
From: aznmark

> Not that. Sorry. Kind of worded "bridge" wrong. But the dock entrance path leading towards the first ship.

**Comment by Terranzin** [comment]
Hello aznmark,

I´ve reviewed your issue once again, and tried on both the bridge UP to the first ship, and also the dock entrence. I´m not able to reproduce this issue you´re telling me about. 

Could you please send more proof of this issue, exactly the location?

![image](https://user-images.githubusercontent.com/25831382/32914273-49245d0c-cb15-11e7-9308-8c0ec0a5f079.png)

![image](https://user-images.githubusercontent.com/25831382/32914307-63c61286-cb15-11e7-8d9a-5c9eb7eaaf43.png)
![image](https://user-images.githubusercontent.com/25831382/32914373-a2cabebe-cb15-11e7-8d27-ffe10746c020.png)

**Comment by Navashed** [comment]
Reproduced.

![los issue 7](https://user-images.githubusercontent.com/2709545/33447007-e2d353b2-d5cf-11e7-857d-e7169ddc655e.jpg)
![los issue 4](https://user-images.githubusercontent.com/2709545/33447061-047ce38e-d5d0-11e7-8053-23a7abbfd2ce.jpg)

Occurs on other docks as well:
![los issue 5](https://user-images.githubusercontent.com/2709545/33447075-16548bac-d5d0-11e7-8d6f-49887fa2e328.jpg)
![los issue 3](https://user-images.githubusercontent.com/2709545/33447082-2012cc9e-d5d0-11e7-927a-869929cd9f4f.jpg)
![los issue 2](https://user-images.githubusercontent.com/2709545/33447115-3bf81f18-d5d0-11e7-96d9-f9d65f716ec8.jpg)

How LoS should work, for reference:
![no los issue](https://user-images.githubusercontent.com/2709545/33447129-4ae8147e-d5d0-11e7-8661-c2c6b2d467e4.jpg)

I believe the issue is caused by the fact that docks overhang terrain. The game is probably raycasting for LoS from the terrain under the dock, rather than the player's location on top of the dock as would be correct.
