### ISSUE TITLE
Elemental Damage on Ranged Weapons does not work (ex: Venomstrike)

### ISSUE THREAD

**Issue by axermaneu** [elysium-project/bug-tracker#490]
https://vanilla-twinhead.twinstar.cz/?item=6469#wh-comments the Venom shot does not work.

**Comment by Terranzin** [comment]
Hello,

I´m not understanding your reported issue, is it serpent sting that doesn´t work together with the bow Venomstrike? Please reply back so we can test these things out.

**Comment by axermaneu** [comment]
There is no additional damage nature. 

"Equip: Chance to strike your ranged target with a Venom Shot for 31 to 46 Nature damage"
Venom shot not working!!!
![venomstrike](https://user-images.githubusercontent.com/36839334/36686996-4bcb9f6a-1b39-11e8-94fd-56f55efb6122.jpg)

**Comment by Navashed** [comment]
This issue was already reported and confirmed. #325 

I see the issue was not understood by the devs and thus closed without being fixed. I will restate it more clearly here:

In this patch, Venomstrike does not have that proc.
Instead, it has an elemental damage component on its regular attack:
![venom](https://user-images.githubusercontent.com/2709545/36688386-4ab896d0-1afa-11e8-8d46-97fb621f23d7.png)
"+ 3 - 6 Nature Damage" on every attack.

This elemental damage can be found on many weapons. I gave an extensive list in #325 although there may be more. The elemental damage does not currently work on any item.

**Comment by Navashed** [comment]
From Patch 1.12 notes:

> Ranged Elemental Damage: Our ranged combat system does not allow a ranged weapon to do a mix of Elemental (Fire, Frost, Arcane, etc.) and Physical damage. Many ranged weapons existed which were listed as doing Elemental damage and did not function properly (the damage was dealt, but was treated as Physical). All of those weapons have been changed to deliver the Elemental damage as a chance on hit effect. Hurricane was previously changed this way in 1.11. The following ranged weapons are also fixed in 1.12: Bow of Searing Arrows, Dwarven Hand Cannon, Heartseeking Crossbow, Dark Iron Rifle, Galgann's Fireblaster, Quillshooter, Shell Launcher Shotgun, Venomstrike, and Verdant Keeper's Aim.

**Comment by Navashed** [comment]
Confirmed that the current functionality is Blizzlike pre-1.12. However, since Blizzard considered this functionality a "bug" and "not functioning properly," I am of the opinion that these items (ranged weapons with +elemental damage) should be changed to their 1.12 versions.

**Comment by sidsukana** [comment]
Damage included in white damage, It's not a bug.
