### ISSUE TITLE
Meet at the Grave

### ISSUE THREAD

**Issue by zhuk90** [elysium-project/bug-tracker#492]
after completing this task, no experience is accumulated in the amount of 7 thousand 250

**Comment by Navashed** [comment]
Confirmed.

Quest 3912 - Meet at the Grave should give 5100 XP (source: https://web.archive.org/web/20070318164436/http://thottbot.com:80/q3912)

Currently it is attempting to give 7250 XP but it is giving 0. I think this is happening because the player is dead when they hand the quest in.

![a6c988b447854392831d60d5e2411e90](https://user-images.githubusercontent.com/2709545/36877102-89bfe75a-1d86-11e8-9346-26a77f209372.png)
![f96df35a8caa83856e235b52a95d5c5a](https://user-images.githubusercontent.com/2709545/36877104-8c063078-1d86-11e8-92e3-604e39fa624b.png)
