### ISSUE TITLE
Zeppelins bugged and flagging for PvP between Durotar and Tirisfal Glades

### ISSUE THREAD

**Issue by voranir** [elysium-project/bug-tracker#505]
- Affecting Nighthaven PvP server, current and all previous patches

- Behavior: When zoning between Durotar and Tirisfal Glades riding the zeppelin, it always flags you for PvP (in both directions).

- Expected Behavior: This zeppelin is not supposed to flag you for PvP, as you are travelling from one safe zone to another. In classic Vanilla, it did not flag you.

Issue #400 claimed to have fixed this, and it was fixed... temporarily. It is now bugged again.

**Comment by sidsukana** [comment]
A week ago, when there were massive lags on the server, it was decided to rollback the last update. Your report is not relevant.

**Comment by voranir** [comment]
So you want people to report shit or you just want to insult them? What the hell. The report is marked as fixed still, and its not fixed. Completely relevant.

**Comment by fulzamoth** [comment]
Note: As a general rule, issues marked *Fixed* may not be in production yet.

The bug was fixed, but as Sid noted, the update was rolled back due to lag issues that appeared after the change. "Not relevant" is just a bad translation of "not an issue that needs to be fixed by devs", not an insult. It's already fixed, and just awaiting the other problems to be sorted before it's re-applied in prod.
