### ISSUE TITLE
Dead pet dissapears when player dies/Pet loses its for "unknown" reason

### ISSUE THREAD

**Issue by Hanzemon** [elysium-project/bug-tracker#528]
1. When your pet dies and it happens that your character also dies the corpse of the pet dissapears, then you have to summon your dead pet (which is kinda creepy) an then resurrect it, this is incorrect; the corpse of the pet must remain upon the death of your character, it only should be dismissed if you get too far from it. I have played in different Vanilla servers and this is the only one that has this issue, so I'm quite sure it is not working as intended. Also it is true that when you resurrect and your pet didn't die previously you have to summon it because it dismiss automatically when youdie, in that case when the pet is alive it is correct that you have to summon it after resurrecting.

2. For some reason (probably related to the previous issue) my pet's name is "Unknown" in its tooltip and in the nameplate, while in the unit frame it is blank. I have assigned a name to it in the past, it was "Polar". Now the name is "Unknown" and there is no way for me to change it.

![capture 1](https://user-images.githubusercontent.com/32701428/37032875-5ad3395a-211a-11e8-90f6-cdf42bff7270.jpg)

**Comment by Thenari** [comment]
yeah warlocks sacrifice pets a lot i know this one, but it hasn't happened to me in a long time.
the whole unknown pet name thing, the hunter summoning dead pets because they despawn makes sense, these pets are not perm like players they are just "summoned" and if you die your summon breaks, if they die, there body stays until a new version of them is created, but im sure they can time out and despawn for a bunch of reasons.

either way this isnt a super vital bug its just a name thing

pretty sure it was fixed or mostly fixed though since you posted this and when i finally got a chance to look at the backlog
