### ISSUE TITLE
The Lich, Ras Frostwhisper

### ISSUE THREAD

**Issue by Brunelleschino** [elysium-project/bug-tracker#529]
The spell cast by the quest item will channel and enable you to loot his head, yet the animation (Ras turning into a human) is missing entirely, and thus it is impossible to verifiy if the spell was successful.

https://classicdb.ch/?quest=5466

**Comment by YaboyJimmyrustle** [comment]
While the animation of Ras turning into a human is absent, the quest item is functioning properly. You are currently able to channel Boon of Life and loot his head after he dies if the channeling was fully completed. You may channel Boon of Life as many times as needed. Looting the head is confirmation the spell was successful and is verifiable, however, the animation is a necessity that would make it clearer the spell was applied. 

Since the animation is indeed missing, I will label this as confirmed.

![boon of life combat log](https://user-images.githubusercontent.com/36592168/37202933-ee3270c6-2340-11e8-9215-9403ce039e31.png)
![channeling boon of life](https://user-images.githubusercontent.com/36592168/37202934-ee51d13c-2340-11e8-85dc-21716d4e4538.png)
![looting ras head](https://user-images.githubusercontent.com/36592168/37202935-ee6aa3d8-2340-11e8-9e3b-ff6d2bede52c.png)
