### ISSUE TITLE
Zeppelin ride flags for PVP

### ISSUE THREAD

**Issue by h4rr0d** [elysium-project/bug-tracker#53]
When flying zeppelin from Orgrimmar to Tirisfal Glades, the zeppelin never leaves horde territory, yet horde players get flagged for PVP. This should not happend (and I'm fairly sure it didn't happen on vanilla either)

**Comment by Terranzin** [comment]
I´ve reviewed your issue and managed to reproduce the fault. You shouldnt as a player get marked with PVP-flag when using this zeppelin since you´re still in a horde territory, and by that it means the two nearest low level zones near a city.

I was trying to see if "The Great sea" had some weird collision as if it was counted as a horde territory or not by visiting where the zeppelin appears, but my pvp-flag did not trigger.
![image](https://user-images.githubusercontent.com/25831382/32962391-8dbf0e96-cbcc-11e7-966f-3f4830a6c905.png)

 There seems to be something in the event as you spawn, that flags you with PVP-flag.

**Comment by Katanya06** [comment]
This hasn't been fixed, and frankly its getting annoying that we CAN'T get to our major cities without the alliance exploiting this bug.
