### ISSUE TITLE
Axe of the Deep Woods broken?

### ISSUE THREAD

**Issue by stephvass** [elysium-project/bug-tracker#590]
Axe of the Deep Woods, an epic lvl52 one hand axe does not seem to proc.  It's trait blasts the target with nature dmg, I am an elemental shaman and perhaps my nature +dmg is impacting it? I am using Storm Gauntlets which add +3 dmg on melee hits, I wonder if this is confusing it? Either way, the Axe does not seem to proc at all. I'd really like to know why.

**Comment by YaboyJimmyrustle** [comment]
Axe of the Deep Woods is proccing properly. The animation for the proc looks like an earth shock so it could be overlooked easily by a shaman if you're using that spell. It will also show up in damage meters as "Wrath" because of the nature damage classification. As far as I've observed, neither windfury weapon, nor any +damage enhancements have any effect on the proc rate. The proc rate is fairly low, so you might not see it all too often at ~3% based on my testing. All that being said, Axe of the Deep Woods is functioning as intended.
