### ISSUE TITLE
Grime-Encrusted Ring drop rate

### ISSUE THREAD

**Issue by liskamic** [elysium-project/bug-tracker#68]
Please check the drop rate on [Grime-Encrusted Ring](http://db.vanillagaming.org/?item=9326).
After 4 full Gnomergan runs and killing estimated 100 dwarves: the probability that it DID NOT drop for me is less than 0.003 %.
It should drop from Dark Iron Agents with 10% probability.

**Comment by Terranzin** [comment]
I´ve reviewed your issue, you can´t use db.vanillagaming.org as a reference. According to old archives the Grime-Encrusted Ring drop rate is around 0,6% and not 10%. Do remember, your procentage does not increase because you kill more mobs, its still 0,6% on each enemy you kill.

If you dont think it exists on the loot table, please ask a GM to validate this for you, but the percentage is not 10%.

**Comment by liskamic** [comment]
Ah, yes, thank you. Didn't realize the percentages there are inaccurate.

And yes, even though the number of mobs killed doesn't increase the chance on the next drop, the probability of NOT dropping an item x times in the row is (1 - droprate%/100)^x which gives 0.994^100 = 0.55; so over 0.5 %. Which I admit is not that unlikely. I must have been just unlucky.

Thank you for reviewing the issue.
