### ISSUE TITLE
Reckoning (Prot pally talent)

### ISSUE THREAD

**Issue by Peachusftw** [elysium-project/bug-tracker#72]
The talent only works partially. While you get the extra attack when critically hit, you can only store up to 1 instance of Reckoning proc. This is flawed due to fact that the Reckoning should be able to stack up to 5 instances.

Proof: (I'm sorry, while there are numerous threats and videos regarding the talent, I couldn't find a better description on offical pages)

http://wowwiki.wikia.com/wiki/Reckoning_Bomb       - See the hotfix 

Regards, Peachus

**Comment by Terranzin** [comment]
I´ve reviewed your issue and I can´t reproduce the error you´re mentioning. I pulled a pack of enemies and made them crit me for 5+ times. After a couple of seconds I turn around and did just one single hit which turns out to become 5 (because of reckoning).

![image](https://user-images.githubusercontent.com/25831382/33038841-3f67e616-ce36-11e7-9dc5-09f10c245f37.png)
