### ISSUE TITLE
Death Coil (desync)

### ISSUE THREAD

**Issue by CRazY-LeMoN** [elysium-project/bug-tracker#743]
После применения заклинания варлока Death Coil (https://classicdb.ch/?spell=17926) в PvP, противник, после окончания страха, оказывается в месте, отличным от того, где он находился в страхе

**Comment by drozdez** [comment]
Если не сложно, опишите немного конкретнее, что Вы имеете в виду, когда говорите, что противник оказывается в ином месте?

**Comment by CRazY-LeMoN** [comment]
https://youtu.be/Mc1ghf96ms4

**Comment by Thenari** [comment]
Yo, I got a vague idea of whats going on here because of google translate.

So death coil Would send player characters in a direction but their initial trajectory was where they would end up? I've only played warlock and never noticed it do that...

you put the fixed label so if you feel it is dealt with close this thread.

Thanks for stepping in Dr. D!
