### ISSUE TITLE
Linken's Adventure

### ISSUE THREAD

**Issue by Jayclen** [elysium-project/bug-tracker#746]
Completed the quest previous, have all the items in my bag and the quest chain just stops even though there are 2 more quests in the chain. I even had another quest ready to accept and when I hit accept it said I didn't meet the requirements.

**Comment by Thenari** [comment]
Yeah after handing in a chain quest the next quest will start writing its quest log regardless of your lvl. When you try to accept thats when the quest checks you level. Can you name what quest you are trying to accept and what level you are.

**Comment by Jayclen** [comment]
The quest is called Linken's Adventure and I'm level 53 as I'm trying to accept it currently. However every time I go back the npc who gives the quest out J.D. Collie doesn't have the quest for me to accept.

**Comment by Thenari** [comment]
https://classicdb.ch/?quest=3961

That quest starts at lvl 54

**Comment by Bashallot** [comment]
Actually this quest should be available at 47 - see link. It has a "level" of 54 which is just the "ideal" level.
I wanted to open a ticket about when some quests become available since I've noticed several which are not available despite classicdb or wowhead stating they should. I am currently level 49 and have done this chain up to A Gnome's Assistance which is now grey ! for me.  The whole Linken Chain "requires" 47 despite the level going from 52 to 56
