### ISSUE TITLE
[Mob] Pet Imp doesn't attack in Desolace

### ISSUE THREAD

**Issue by Stoley** [elysium-project/bug-tracker#91]
> Trampy - Today at 1:50 PM
> I noticed last night while killing mobs in Desolace, Mannoroc Coven to be precise, and doing the portal destruction quest that the warlock mobs there with imp pets are a little buggy. 
> 
> The warlocks attack as per normal but their pet imp just stands there and does nothing. After killing the warlock the imp follows you until you kill it.

**Comment by Terranzin** [comment]
I´ve reviewed your issue and I manage to reproduce the error. 

Burning Blade Summoner (NPC id: 4668) has a pet with him, that gets spawned with spellId: 688. What I attempted was just to aggro the summoner, but the pet seems to only look at the player, not actually assist the summoner, tried both standing long range and melee range from his pet, nothing seemed to bother him.

![image](https://user-images.githubusercontent.com/25831382/33234616-a1ec95e6-d22a-11e7-8c36-d20b9e92e7fa.png)

**Comment by Navashed** [comment]
Pet is supposed to cast Firebolt. Imps do not have autoattack (this is correct). If you silence an Imp he will just stand there (this is correct).

Only problem is he is missing Firebolt (or he is not casting it for some reason if he does have the spell). I can't link Spell ID because I am not sure which Firebolt the NPC imps are supposed to use.
